sudo: required
services:
  - docker
before_install:
  - docker build -t react-web -f Dockerfile.dev .
script:
  - docker run react-web npm run test -- --watchAll=false
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-test"
  env: "DockerReactTest-env"
  bucket_name: "elasticbeanstalk-us-east-1-308454549890"
  bucket_path: "docker-react-test"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
